[workspace]
members = [
  "bot",
  "backend",
  "database"
]
resolver = "2"

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
backend = { path = "backend/" }
database = { path = "database/" }

poise = "0.6.1"
tokio = { version = "1.37.0", features = ["rt-multi-thread", "signal"] }

dotenv = "0.15.0"
log = "0.4.21"
env_logger = "0.11.3"

fancy-regex = "0.13.0"

lazy_static = "1.4.0"
serde = { version = "1.0.0", features = ["derive"]}
serde_json = "1.0.0"

[profile.release]
strip = true      # Automatically strip symbols from the binary.
lto = true        # Link-time optimization.
opt-level = 3     # Optimize for speed.
codegen-units = 1 # Maximum size reduction optimizations.
