[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
log.workspace = true

poise.workspace = true
fancy-regex.workspace = true
serde.workspace = true
serde_json.workspace = true
lazy_static.workspace = true
