[package]
name = "midnight-model"
edition = "2024"
version.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
diesel.workspace = true
serde.workspace = true
serde_json.workspace = true
smallvec.workspace = true

[lints]
workspace = true
