[package]
name = "common"
edition = "2021"
version.workspace = true

[dependencies]
lazy_static.workspace = true
once_cell.workspace = true
serenity.workspace = true
sysinfo.workspace = true
tokio.workspace = true

[lints]
workspace = true
